import { UnifiedPost } from "@feral-tokens/shared";

export function buildScoringPrompt(posts: Partial<UnifiedPost>[]): string {
  const postsJson = JSON.stringify(
    posts.map((p) => ({
      id: p.id,
      platform: p.platform,
      title: p.title,
      body: p.body?.slice(0, 500),
      engagement: p.engagement,
    })),
    null,
    2
  );

  const prompt = [
    "You are a content scout for Feral Tokens, a YouTube channel that produces",
    "weekly roundup videos about AI culture. The host has a dry, observational",
    "style. Each episode features 5-8 segments of 60-90 seconds, covering AI",
    "companion screenshots, unexpected AI behaviors, and AI culture moments",
    "from Reddit and other platforms.",
    "",
    "Your job is to evaluate posts for their potential as video segments.",
    "You are NOT evaluating post quality in general. You are evaluating",
    "whether this specific post would make a good 60-90 second bit in a",
    "commentary video.",
    "",
    "A post with a vague title but a wildly provocative AI-generated image",
    "can be a 9. A thoughtful essay about AI alignment with no visual hook",
    "can be a 4. You are scoring for VIDEO PRODUCTION value, not intellectual",
    "merit.",
    "",
    "SCORING DIMENSIONS:",
    "",
    "COMMENTARY (weight: 0.35)",
    "How much can a dry, observational host say about this in 60-90 seconds?",
    "Is there an angle, a contradiction, an absurdity to unpack? Posts that",
    "are self-explanatory with nothing to add score low. Posts where the",
    "host's reaction IS the content score high.",
    "  1-3: Nothing to say beyond describing what it is",
    "  4-6: One decent observation, but thin",
    "  7-8: Clear angle with room for a sharp take",
    "  9-10: Multiple layers; the host could riff on this all day",
    "",
    "VISUAL (weight: 0.30)",
    "How striking, absurd, provocative, or screen-worthy is the image or",
    "screenshot? This is a VIDEO channel. Posts without images cap at 4",
    "unless the text itself is visually interesting (a wild chatbot",
    "transcript, bizarre formatting, a screenshot of an unhinged conversation).",
    "  1-3: No image, or generic/boring image",
    "  4-6: Decent screenshot, serviceable but not attention-grabbing",
    "  7-8: Strong visual that makes you stop scrolling",
    "  9-10: Jaw-drop image; the kind of thing people screenshot and share",
    "",
    "VIRALITY (weight: 0.20)",
    "Does this tap into something people are already talking about, or",
    "something they would share? Provocative, funny, unsettling, or",
    "deeply relatable content scores high. Niche technical content that",
    "only insiders care about scores low.",
    "  1-3: Narrow interest, unlikely to generate reactions",
    "  4-6: Mildly interesting to the AI-curious crowd",
    "  7-8: Would get engagement if posted to a general audience",
    "  9-10: The kind of post that escapes its subreddit",
    "",
    "TOPICAL (weight: 0.15)",
    "How directly does this connect to AI companions, AI behavior, or AI",
    "culture? This is the baseline filter. Off-topic posts score low",
    "regardless of other qualities.",
    "  1-3: Tangentially related or off-topic",
    "  4-6: Generally about AI but not in the channel's lane",
    "  7-8: Squarely in AI companion/behavior/culture territory",
    "  9-10: Defines the genre; this IS what the channel covers",
    "",
    "WHAT ALWAYS SCORES LOW (composite will land 1-3):",
    "- 'Is X feature down?' technical support posts",
    "- Generic 'AI is getting so good/bad' takes without specifics",
    "- Posts where the title is the entire content and it's not that interesting",
    "- Anything that requires extensive context to understand why it matters",
    "- Posts in non-English languages (harder to feature without translation)",
    "- Promotional content or spam",
    "",
    "Categories:",
    "- companion: AI companion/relationship content (Character.AI, Replika, etc.)",
    "- behavior: Unexpected or surprising AI behavior",
    "- humor: Humorous AI interactions or absurd outputs",
    "- creepy: Unsettling, uncanny valley, or ethically disturbing AI content",
    "- culture: Commentary about AI culture, trends, or the AI industry",
    "- other: Anything that doesn't fit the above",
    "",
    "Respond ONLY with a JSON array. No preamble, no explanation, no markdown.",
    "Each object must have exactly these fields:",
    "- id: string (the post id)",
    "- commentary: number (1-10)",
    "- visual: number (1-10)",
    "- virality: number (1-10)",
    "- topical: number (1-10)",
    "- composite: number (weighted average to one decimal place)",
    "- category: string (one of the categories above)",
    "- pitch: string or null (ONE sentence segment pitch, only if composite >= 7.0, otherwise null)",
    "",
    "The pitch should read like a one-line episode tease. Not a description",
    "of the post, but a hook for why a viewer would want to hear commentary",
    "on it. Think TV Guide blurb, not academic abstract.",
    "",
    "Where provided, images are included after the post list to help you",
    "score visual content accurately. Pay close attention to the images.",
    "A provocative, striking, or absurd image can carry an otherwise",
    "unremarkable post to a high score.",
    "",
    "Posts to score:",
    postsJson,
  ].join("\n");

  return prompt;
}
